### ISSUE TITLE
Cannot read scheme peel.icls from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142

### ISSUE THREAD

**Issue by farranfox** [lstables/phpstorm-settings#2]
I imported settings, restart phpstorm and got:

1) Cannot read scheme peel.icls from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142
2) Cannot read scheme FaceBook.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142
3) Cannot read scheme laracasts_theme_updated.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142

Ubuntu 14.04

**Comment by lstables** [comment]
Not sure I dont use Ubuntu
