### ISSUE TITLE
Settings don't work on phpstorm 9/windows 7

### ISSUE THREAD

**Issue by bicatu** [lstables/phpstorm-settings#4]
Hi,  when I imported the settings it complains about at every startup

Cannot read scheme peel.icls from $ROOT_CONFIGS/colors : unsupported color scheme version 142
Cannot read scheme Facebook.icls from $ROOT_CONFIGS/colors : unsupported color scheme version 142
Cannot read scheme laracasts_theme_updated.icls from $ROOT_CONFIGS/colors : unsupported color scheme version 142

If you don't support - or plan to support - on other platforms I'd respectfully mention this and, if possible, post some tips on how to make those errors go away.

**Comment by lstables** [comment]
Sorry not sure why this would be I don't use Windows so I can't comment.

Have you Googled these errors?
