### ISSUE TITLE
This Changed All of My Keymappings

### ISSUE THREAD

**Issue by ghost** [lstables/phpstorm-settings#5]
Hello,

This changed all of my key mappings.  For instance, instead of ctrl-shift-a there is now a new keymapping meta-shift-a.

I have no idea what the meta key refers to, but either way I would like my old key mappings back.  Any idea how to do that?  Or, alternatively, how to uninstall the settings import I did?

Thanks,

Moshe

**Comment by lstables** [comment]
Just remove the import from your applications folder and should be fine
